print("hello everyone")
a=input("enter 1st number :")
b=input("enter 2nd  number :")
sum=int(a)+int(b)
difference=int(a)-int(b)
product=int(a)*int(b)
quotient=int(a)/int(b)
print("sum is :",sum)
print("difference is :",difference)
print("product is :",product)
print("quotient is :",quotient)